bchew/dynamodump

README.md, dynamodump.py
Added option to backup/restore all tables (* wildcard) and restore data only (useful for batch loading data). Default write capacity is now 25 to stay within free tier.
=> Support backup/restore of all tables (*) and data only restore mode.

dynamodump.py
A unicode value is garbled under the current version (ex \uXXXX). So I modified it.
=> Support unicode value 

dynamodump.py
=> Revert "Support unicode value "

README.md, dynamodump.py
Flush Database drops the table and recreates it, easy way to delete all the data
=> Added Flush Parameter

.travis.yml, README.md, dynamodump.py
Adds:
* Changes to pass flake8 tests, while ignoring the long lines test (E501).
* A very basic travis.yml. I can imagine it would be constructive to test using https://github.com/mhart/dynalite .
* Travis badge, needs enabling of Travis builds for your account
=> Travis, PEP8

.travis.yml, test/test.py, test/testTable/data/0001.json, test/testTable/schema.json
Added basic backup/restore tests using dynalite, hooked up to Travis CI
=> Add basic tests using dynalite

README.md
a few changes not captured in the README
=> update help/usage text

.gitignore, dynamodump.py
Refactored main code into a main method to allow importing of dynamodump script into other python scripts.
=> Allow dynamodump to be imported as a module

dynamodump.py
Wildcard matching didn't work when I used `*` or `table-*`. I fixed it.
=> Correct wildcard matching

README.md
Update readme with latest help output, docker build badge
=> Update readme with latest help output, docker build badge

.travis.yml, test/test.py
- Add python 3.6 to .travis.yml
- Fix file open warnings in tests for python3
=> Make CI test python 2 and 3

.github/workflows/linting.yml, .github/workflows/test.yml, README.md
=> ci: split actions workflow

.gitignore, dynamodump.py, requirements.txt
Problem:
having the boto2 dependency makes it more complicated to use e.g. proxies, 
also it is more readable using the named exceptions from boto3 
I've also added boto3 typings
=> remove boto2 dependency

.github/workflows/build.yml
Remove additional newline at end of actions build workflow
=> ci: remove additional newline at eof

.dockerignore, .github/workflows/docker.yml, README.md
Set up automated Docker image publish via GitHub Action workflow as previous automated builds on Docker Hub no longer works
=> Add Docker Hub publish action

.github/workflows/docker.yml
Remove on pull request from docker image publish action
=> ci: remove pr trigger from docker publish

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add devcontainer configuration for VS Code Remote - Containers development usage: https://code.visualstudio.com/docs/remote/containers
=> chore: add vscode devcontainer configuration

.github/dependabot.yml
Add dependabot version updates
=> ci: add dependabot version updates

.github/workflows/codeql-analysis.yml
Add CodeQL analysis GitHub action
=> ci: create codeql-analysis.yml

.github/dependabot.yml
Update dependabot to cover Dockerfile updates
=> ci: update dependabot to cover dockerfile updates

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml, .pre-commit-config.yaml, Dockerfile
Upgrade default python usage to 3.10
=> chore: upgrade default python usage to 3.10

README.md, dynamodump/dynamodump.py
Add billing mode option feature done by @bashou in https://github.com/bchew/dynamodump/pull/90 to support `PAY_PER_REQUEST` and retain default of `PROVISIONED`
=> feat: add billing mode option

.github/workflows/stale.yml
=> ci: add stale github action

.github/workflows/dependency-review.yml
Add dependency review github action
=> ci: add dependency review github action

Dockerfile
Upgrade dockerfile to latest python 3.10
=> chore: upgrade dockerfile to latest python 3.10

.flake8, .pre-commit-config.yaml, requirements-dev.txt
- Upgrade flake8 to v5
- Add W503 to flake8 extend-ignore
=> chore: upgrade flake8 to v5

dynamodump/dynamodump.py
Fix some code smells found by sonarcloud
=> fix: fix some code smells found by sonarcloud

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml, Dockerfile
=> chore: use python 3.11

renovate.json
=> ci: fix renovate schedule config

dynamodump/dynamodump.py
Fix SonarCloud bug introduced in
=> fix: fix limit change

README.md
=> chore: update usage in readme

.github/workflows/test.yml, setup.py
=> ci: drop eol python 3.7

README.md
Update links to container registries
=> docs: update links to registries

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml, .pre-commit-config.yaml, Dockerfile
=> chore: add/upgrade to python 3.12

.devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/linting.yml, .github/workflows/test.yml, .pre-commit-config.yaml, setup.py
Support python 3.13 and drop EOL-ed 3.8
=> chore: support python 3.13 and drop eol-ed 3.8
