dynamodump.py

Used when tables are prefixed without a separtor e.g.
testTableOne
testTableTwo
can be backed up with:
./dynamodump.py -m 'backup' -r 'ap-southeast-2' --prefixSeparator '' -s 'test*'
and restored with:
./dynamodump.py -m ‘backup’ -r 'ap-southeast-2' --prefixSeparator '' -s 'test*' -d 'prod*'
Resulting restored tables would be:
prodTableOne
prodTableTwo

support blank prefix separator and use case instead

---

README.md
dynamodump.py

The --schemaOnly option allows the user to backup and restore
just the schema information for the given table(s). The use
case for this is if you need to migrate your tables from one
AWS account to a different AWS account.
(Our specific use case: We have an AWS account for development
and yet a separate AWS account for production.)
To support the use case of multiple AWS accounts, -p or --profile
was also added so that the user could explicitly specify which
profile to use from the AWS credentials file (~/.aws/credentials).
This is /slightly/ more secure than putting accessKey and
secretKey into the command line.

Added schemaOnly and AWS credentials support

---

dynamodump.py
test/test.py

I noticed that my restores were failing for two reasons:
- I did a `--dataOnly` restore, which doesn't update the capacity limits, so moved some code around to make that happen
- If you don't want to change the capacity limits for whatever reason, and the limits are too low, the batch write fails because it doesn't sleep between tries (I expected boto to do that but apparently it doesn't), I added a simple "linear sleep" which solves that (although it could be improved by using "exponential sleep" instead of linear)
These fixes work for me, I haven't tested it thoroughly. Hope it's useful!

batch write sleep interval and provisioned capacity limits on data only restore

---

dynamodump.py

1. Added `Prefix` to the `s3.list_objects_v2` request to speed up the search.
1. Fixed a bug related to filename mapping during restore; should use `args.dumpPath` instead of`dump`.

Minor fix in do_get_s3_archive

---

Dockerfile

Update Dockerfile to use python:3.9.0-alpine3.12 base image

chore: update Dockerfile to use python:3.9.0-alpine3.12 base image

---

.github/workflows/linting.yml
.github/workflows/test.yml
dynamodump/dynamodump.py
setup.py
tests/test.py

- Support absolute path usage for `dumpPath` argument (pulled from https://github.com/bchew/dynamodump/pull/68), thanks @Ram-dev06
- Add more tests to cover non-default and absolute dump path usages
- Refactored test GitHub Actions workflow to parallelise addtional tests, add Python versions >=3.6 to strategy matrix
- Bump version to 1.4.0

feat: support absolute path for dumpPath

---

docker-compose.yml
test.sh

- Add DynamoDB Local via docker-compose
- Add tests shell script for running basic tests locally

chore: add dynamodb-local via docker-compose and tests shell script

---

.pre-commit-config.yaml

Update to match version from dependabot upgrade: https://github.com/bchew/dynamodump/pull/84

chore: update black in precommit to match dependabot upgrade

---

.github/dependabot.yml

Ignore `boto3` patch updates in dependabot

ci: quieten dependabot for boto3 patch updates

---

dynamodump/dynamodump.py

- Sort imports and variables alphabetically
- Drop Python2 support in imports

chore: sort imports and variables

---

dynamodump/dynamodump.py

The boto3 API expects GlobalSecondaryIndexUpdates instead of global_secondary_index_updates in the parameter section of the method call. This PR fixes this single inconsistency of the API. Documentation of boto3 API call -> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.update_table

Fixes boto3 DynamoDB update_table API call

---

.github/workflows/docker.yml

AWS approved `bchew` as custom alias for public ECR thus switching to that for consistency

chore: update ecr uri to use custom alias

---

Dockerfile

This issue was brought up in https://github.com/bchew/dynamodump/pull/111, fixed it instead to use `CMD` as the default flags per https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

fix: fix entrypoint in Dockerfile

---

dynamodump/dynamodump.py

fixed linting from PR #109 submitted by @FlorianBruckner

pass endpoint_url for local dynamodb with linting

---

README.md
dynamodump/dynamodump.py

Support for filter option when backup
Use JSON file to get filter options provided by boto3
Accept only three options otherwise raise exception. 
**FilterExpression, ExpressionAttributeNames, ExpressionAttributeValues**
See descriptions in [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.scan)

Add filter option for backup

---

.github/workflows/test.yml
setup.py

In line with boto3 support deprecation https://github.com/boto/boto3/pull/3278

chore: drop support for EOL python 3.6

---

test.sh

Use docker compose without hyphen as `docker-compose` is deprecated

fix: use docker compose without hyphen

---

.github/workflows/test.yml

I setup the project to run with Python 3.11 and then spin up the `dynamodb-local` via Docker compose and ran `test.sh`. All looked good, therefore I added it to the CI 🙂

add Python 3.11 support

---

.sonarcloud.properties

Add `sonar.python.version` to fix sonarcloud warning

ci: add sonar.python.version to fix sonarcloud warning

---

README.md
dynamodump/dynamodump.py

I ran into this issue myself and was able to get the tool working by changing the behavior switch to key off of the use of the `host` parameter instead of the `local` region. This improves compatibility with other methods of mocking AWS behavior which strictly mimic the actual regions without breaking compatibility with local scripts since `host` was only used with `local` anyway.

Resolve #156 Incompatible with Localstack

---

dynamodump/dynamodump.py
setup.py

Fixes issues in create_table, when table has local secondary indexes

Pass only required attributes of LSI's while creating table

---

dynamodump/dynamodump.py

1. Added support to back up and restore bytes data.
2. Added new flags to stop the backup process after reached certain limit.

Support dump and load bytes and add back up limit

---

.pre-commit-config.yaml

Update black pre-commit as per integrations note in https://github.com/psf/black/releases/tag/23.9.0

ci: update black pre-commit

---

dynamodump/dynamodump.py

My source table has billing_mode PAY_PER_REQUEST and some global secondy indexes from this table too.
This change will fix the error below:
```bash
dynamodump -m restore -p profile -s sourceTable -d targetTable -r region --billingMode PAY_PER_REQUEST
About to delete table targetTable. Type 'yes' to continue: yes
INFO:botocore.tokens:Loading cached SSO token for profile
INFO:root:targetTable table deleted!
INFO:root:Starting restore for sourceTable to targetTable..
INFO:root:Creating targetTable table with temp write capacity of 25
ERROR:root:An error occurred (ValidationException) when calling the CreateTable operation: One or more parameter values were invalid: ProvisionedThroughput should not be specified for index: my-index when BillingMode is PAY_PER_REQUEST
Traceback (most recent …
```

fix: globalSecondaryIndex PAY_PER_REQUEST

---

dynamodump/dynamodump.py

Fix KeyError: 'ProvisionedThroughput' which occurs when trying to restore a DynamoDB which is in on-demand mode.

fix: allow restore on-demand mode database (#311)
